---

- name: Set up a new user and restrict ssh for root
  hosts:
    - all
  vars:
    - ansible_user: root
  tasks:
    - action: ping
    - name: Install vim
      ansible.builtin.dnf:
        name: vim-minimal
        state: latest
    - name: Ensure all nessesary groups exist
      ansible.builtin.group:
        name: "{{ item }}"
        state: present
      loop:
        - docker
        - "{{ ansible_control_user }}"
    - name: "Add the user '{{ ansible_control_user }}'"
      ansible.builtin.user:
        name: "{{ ansible_control_user }}"
        comment: "{{ ansible_control_user }}"
        groups: "{{ ansible_control_user }},docker,wheel"
        append: yes
    - name: "Set authorized key for {{ ansible_control_user }}"
      ansible.posix.authorized_key:
        user: "{{ ansible_control_user }}"
        state: present
        key: "{{ lookup('file', ansible_public_key_file) }}"
    - name: "Allow passwordless sudo for {{ ansible_control_user }}"
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'
    - name: Disallow root login
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        state: present
        regexp: '^PermitRootLogin'
        line: "PermitRootLogin no"
        backup: yes
      notify:
        - Restart ssh
  handlers:
    - name: Restart ssh
      ansible.builtin.systemd_service:
        name: sshd
        state: restarted
        daemon_reload: true
